name: Bow Quiver
main: info.trentech.Quiver.Quiver
version: 1.0.1
commands:
  quiver:
    usage: </command>
    description: Quiver Plugin
    aliases: [qv]
permissions:
  Quiver.*:
    default: op
    children: 
      Quiver.reload: true
  Quiver.reload:
    default: op